ForestDamageAssessment/Controllers/HomeController.cs
using ForestDamageAssessment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ForestDamageAssessment.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ForestDamageAssessment/Controllers/ViolationController.cs
using ForestDamageAssessment.BL.Interfaces;
using ForestDamageAssessment.BL.Models;
using ForestDamageAssessment.BL.Services;
using Microsoft.AspNetCore.Mvc;

namespace ForestDamageAssessment.Controllers
{
    public class ViolationController : Controller
    {
        private readonly IExtendedViolationService<TreeFellingViolationService, ITreeViewModel> _treeFellingViolationService;
        private readonly IExtendedViolationService<TreeFellingViolation2Service, ITreeViewModel> _treeFellingViolation2Service;
        private readonly IExtendedViolationService<BushFellingViolationService, IBushViewModel> _bushFellingViolationService;
        private readonly IExtendedViolationService<BushFellingViolation2Service, IBushViewModel> _bushFellingViolation2Service;
        private readonly IExtendedViolationService<BushFellingViolation3Service, IBushViewModel> _bushFellingViolation3Service;
        private readonly IViolationService<DeadFellingViolationService, ITreeViewModel> _deadFellingViolationService;
        private readonly ISeedlingsService _seedlingsService;
        private readonly IPlantationFellingService _plantationFellingService;
        private readonly IForestAreaService _forestAreaViewModelService;
        private readonly IFileModelService _fileModelService;

        public ViolationController(IExtendedViolationService<TreeFellingViolationService, ITreeViewModel> treeFellingViolationService,
            IExtendedViolationService<TreeFellingViolation2Service, ITreeViewModel> treeFellingViolation2Service,
            IExtendedViolationService<BushFellingViolationService, IBushViewModel> bushFellingViolationService,
            IExtendedViolationService<BushFellingViolation2Service, IBushViewModel> bushFellingViolation2Service,
            IExtendedViolationService<BushFellingViolation3Service, IBushViewModel> bushFellingViolation3Service,
            IViolationService<DeadFellingViolationService, ITreeViewModel> deadFellingViolationService,
            ISeedlingsService seedlingsService,
            IPlantationFellingService plantationFellingService,
            IForestAreaService forestAreaViewModelService,
            IFileModelService fileModelService)
        {
            _treeFellingViolationService = treeFellingViolationService;
            _treeFellingViolation2Service = treeFellingViolation2Service;
            _bushFellingViolationService = bushFellingViolationService;
            _bushFellingViolation2Service = bushFellingViolation2Service;
            _bushFellingViolation3Service = bushFellingViolation3Service;
            _deadFellingViolationService = deadFellingViolationService;
            _seedlingsService = seedlingsService;
            _plantationFellingService = plantationFellingService;
            _forestAreaViewModelService = forestAreaViewModelService;
            _fileModelService = fileModelService;
        }

        [HttpGet]
        public IActionResult TreeFelling()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> TreeFellingData(string[] breed, string[] diameter, string[] h, string[] rankH,
            string region, string year, bool isOZU, bool isProtectiveForests, bool isOOPT)
        {
            var forestArea = _forestAreaViewModelService.CreateForestArea(breed, diameter, h, rankH, region, year, isOZU, isProtectiveForests, isOOPT);

            return View(await _treeFellingViolationService.CalculateAsync(forestArea));
        }
        [HttpPost]
        public async Task<IActionResult> TreeFellingDataFromFile(IFormFile uploadedFile,
            string region, string year, bool isOZU, bool isProtectiveForests, bool isOOPT)
        {
            var forestData = new ForestAreaData { Region = region, Year = year, IsOZU = isOZU, IsProtectiveForests = isProtectiveForests, IsOOPT = isOOPT };
            var forestArea = new ForestArea<ITreeViewModel> { ForestData = forestData };
            var fileModel = await _fileModelService.CreateFileModelAsync(uploadedFile);

            return View("TreeFellingData", await _treeFellingViolationService.CalculateFromFileAsync(fileModel, forestArea));
        }
        [HttpPost]
        public IActionResult TreeFellingDataDetails([FromBody] TreeViewModel model)
        {
            if (model == null)
            {
                return NotFound();
            }

            return PartialView("_TreeFellingDataDetailsPartial", model);
        }
        [HttpGet]
        public IActionResult TreeFelling2()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> TreeFelling2Data(string[] breed, string[] diameter, string[] h, string[] rankH,
            string region, string year, bool isOZU, bool isProtectiveForests, bool isOOPT)
        {
            var forestArea = _forestAreaViewModelService.CreateForestArea(breed, diameter, h, rankH, region, year, isOZU, isProtectiveForests, isOOPT);

            return View("TreeFellingData", await _treeFellingViolation2Service.CalculateAsync(forestArea));
        }
        [HttpPost]
        public async Task<IActionResult> TreeFelling2DataFromFile(IFormFile uploadedFile,
            string region, string year, bool isOZU, bool isProtectiveForests, bool isOOPT)
        {
            var forestData = new ForestAreaData { Region = region, Year = year, IsOZU = isOZU, IsProtectiveForests = isProtectiveForests, IsOOPT = isOOPT };
            var forestArea = new ForestArea<ITreeViewModel> { ForestData = forestData };
            var fileModel = await _fileModelService.CreateFileModelAsync(uploadedFile);

            return View("TreeFellingData", await _treeFellingViolation2Service.CalculateFromFileAsync(fileModel, forestArea));
        }
        [HttpGet]
        public IActionResult BushFelling()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BushFellingData(int[] count, string mainForestBreed, string[] breedBush, string[] bushType,
            string region, string year, bool isOZU, bool isProtectiveForests, bool isOOPT)
        {
            var forestArea = _forestAreaViewModelService.CreateForestArea(count, mainForestBreed, breedBush, bushType, region, year, isOZU, isProtectiveForests, isOOPT);

            return View(await _bushFellingViolationService.CalculateAsync(forestArea));
        }
        [HttpPost]
        public async Task<IActionResult> BushFellingDataFromFile(IFormFile uploadedFile,
            string mainForestBreed, string region, string year, bool isOZU, bool isProtectiveForests, bool isOOPT)
        {
            var forestArea = _forestAreaViewModelService.CreateForestArea(mainForestBreed, region, year, isOZU, isProtectiveForests, isOOPT);
            var fileModel = await _fileModelService.CreateFileModelAsync(uploadedFile);

            return View("BushFellingData", await _bushFellingViolationService.CalculateFromFileAsync(fileModel, forestArea));
        }
        [HttpPost]
        public IActionResult BushFellingDataDetails([FromBody] BushViewModel model)
        {
            if (model == null)
            {
                return NotFound();
            }

            return PartialView("_BushFellingDataDetailsPartial", model);
        }
        [HttpGet]
        public IActionResult BushFelling2()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BushFelling2Data(int[] count, string mainForestBreed, string[] breedBush, string[] bushType,
            string region, string year, bool isOZU, bool isProtectiveForests, bool isOOPT)
        {
            var forestArea = _forestAreaViewModelService.CreateForestArea(count, mainForestBreed, breedBush, bushType, region, year, isOZU, isProtectiveForests, isOOPT);

            return View("BushFellingData", await _bushFellingViolation2Service.CalculateAsync(forestArea));
        }
        [HttpPost]
        public async Task<IActionResult> BushFelling2DataFromFile(IFormFile uploadedFile,
            string mainForestBreed, string region, string year, bool isOZU, bool isProtectiveForests, bool isOOPT)
        {
            var forestArea = _forestAreaViewModelService.CreateForestArea(mainForestBreed, region, year, isOZU, isProtectiveForests, isOOPT);
            var fileModel = await _fileModelService.CreateFileModelAsync(uploadedFile);

            return View("BushFellingData", await _bushFellingViolation2Service.CalculateFromFileAsync(fileModel, forestArea));
        }
        [HttpGet]
        public IActionResult BushFelling3()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BushFelling3Data(int[] count, string mainForestBreed, string[] breedBush, string[] bushType,
            string region, string year, bool isOZU, bool isProtectiveForests, bool isOOPT)
        {
            var forestArea = _forestAreaViewModelService.CreateForestArea(count, mainForestBreed, breedBush, bushType, region, year, isOZU, isProtectiveForests, isOOPT);

            return View("BushFellingData", await _bushFellingViolation3Service.CalculateAsync(forestArea));
        }
        [HttpPost]
        public async Task<IActionResult> BushFelling3DataFromFile(IFormFile uploadedFile,
            string mainForestBreed, string region, string year, bool isOZU, bool isProtectiveForests, bool isOOPT)
        {
            var forestArea = _forestAreaViewModelService.CreateForestArea(mainForestBreed, region, year, isOZU, isProtectiveForests, isOOPT);
            var fileModel = await _fileModelService.CreateFileModelAsync(uploadedFile);

            return View("BushFellingData", await _bushFellingViolation3Service.CalculateFromFileAsync(fileModel, forestArea));
        }
        [HttpGet]
        public IActionResult DeadFelling()
        {
            return View();
        }
        [HttpPost]

ForestDamageAssessment/Controllers/ViolationExtraController.cs
using ForestDamageAssessment.BL.Interfaces;
using ForestDamageAssessment.BL.Services;
using Microsoft.AspNetCore.Mvc;

namespace ForestDamageAssessment.Controllers
{
    public class ViolationExtraController : Controller
    {
        private readonly IResinFellingService _resinFellingService;
        private readonly IForestResourceFellingService _forestResourceFellingService;
        private readonly IForestUseService _forestUseService;
        private readonly IFoodResourceFellingService _foodResourceFellingService;
        private readonly IPlacementOfObjectsService _placementOfObjectsService;
        private readonly IRemovalOfSoilsService _removalOfSoilsService;
        private readonly IRemovalOfAnthillsService _removalOfAnthillsService;
        private readonly IDamageToObjectsService _damageToObjectsService;
        private readonly IRemovalOfSignsService _removalOfSignService;
        private readonly IForestPollutionService<ForestPollutionService> _forestPollutionService;
        private readonly IForestPollutionService<ForestPollution2Service> _forestPollution2Service;

        public ViolationExtraController(IResinFellingService resinFellingService, IForestResourceFellingService forestResourceFellingService, IForestUseService forestUseService, IFoodResourceFellingService foodResourceFellingService, IPlacementOfObjectsService placementOfObjectsService, IRemovalOfSoilsService removalOfSoilsService, IRemovalOfAnthillsService removalOfAnthillsService, IDamageToObjectsService damageToObjectsService, IRemovalOfSignsService removalOfSignService, IForestPollutionService<ForestPollutionService> forestPollutionService, IForestPollutionService<ForestPollution2Service> forestPollution2Service)
        {
            _resinFellingService = resinFellingService;
            _forestResourceFellingService = forestResourceFellingService;
            _forestUseService = forestUseService;
            _foodResourceFellingService = foodResourceFellingService;
            _placementOfObjectsService = placementOfObjectsService;
            _removalOfSoilsService = removalOfSoilsService;
            _removalOfAnthillsService = removalOfAnthillsService;
            _damageToObjectsService = damageToObjectsService;
            _removalOfSignService = removalOfSignService;
            _forestPollutionService = forestPollutionService;
            _forestPollution2Service = forestPollution2Service;
        }

        [HttpGet]
        public IActionResult ResinFelling()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ResinFellingData(string[] countTon, string[] breed, string region)
        {
            return View(await _resinFellingService.CalculateAsync(countTon, breed, region));
        }
        [HttpGet]
        public IActionResult ForestResourceFelling()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ForestResourceFellingData(string[] stumps, string[] bark, string[] lub, string[] birchBark, string[] firPaw,
            string[] pinePaw, string[] sprucePaw, string[] brushwood, string[] forestFloor, string region)
        {
            return View(await _forestResourceFellingService.CalculateAsync(stumps, bark, lub, birchBark, firPaw,
            pinePaw, sprucePaw, brushwood, forestFloor, region));
        }
        [HttpGet]
        public IActionResult FoodResourceFelling()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> FoodResourceFellingData(string[] treeSap, string[] wildFuits, string[] wildBerries, string[] wildMushrooms, string[] wildNuts,
            string[] seeds, string[] medicinalPlants, string region)
        {
            return View(await _foodResourceFellingService.CalculateAsync(treeSap, wildFuits, wildBerries, wildMushrooms, wildNuts,
             seeds, medicinalPlants, region));
        }
        [HttpGet]
        public IActionResult ForestUse()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ForestUseData(string square, string price, bool isViolation1, bool isViolation2, bool isViolation3, string region)
        {
            return View(await _forestUseService.CalculateAsync(square, price, isViolation1, isViolation2, isViolation3, region));
        }
        [HttpGet]
        public IActionResult PlacementOfObjects()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> PlacementOfObjectsData(string square, string price, string priceCleaning)
        {
            return View(await _placementOfObjectsService.CalculateAsync(square, price, priceCleaning));
        }
        [HttpGet]
        public IActionResult RemovalOfAnthills()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RemovalOfAnthillsData(string[] diameter, string mainForestBreed, string region)
        {
            return View(await _removalOfAnthillsService.CalculateAsync(diameter, mainForestBreed, region));
        }
        [HttpGet]
        public IActionResult RemovalOfSoils()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RemovalOfSoilsData(string square, int vehicleCount, string mainForestBreed, string region)
        {
            return View(await _removalOfSoilsService.CalculateAsync(square, vehicleCount, mainForestBreed, region));
        }
        [HttpGet]
        public IActionResult ForestPollution()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ForestPollutionData(string priceCleaning)
        {
            return View("ForestPollutionData", await _forestPollutionService.CalculateAsync(priceCleaning));
        }
        [HttpGet]
        public IActionResult ForestPollution2()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ForestPollution2Data(string priceCleaning)
        {
            return View("ForestPollutionData", await _forestPollution2Service.CalculateAsync(priceCleaning));
        }
        [HttpGet]
        public IActionResult RemovalOfSigns()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RemovalOfSignsData(string price)
        {
            return View(await _removalOfSignService.CalculateAsync(price));
        }
        [HttpGet]
        public IActionResult DamageToObjects()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> DamageToObjectsData(string price)
        {
            return View(await _damageToObjectsService.CalculateAsync(price));
        }
    }
}

ForestDamageAssessment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная";
}

<div class="text-center">
    <h1 class="display-4">Оценка размера ущерба от незаконно заготовленной древесины и иных лесных ресурсов</h1>
</div>
<div class="list-group">
    <h4 class="text-uppercase">Незаконная рубка</h4>
    <a asp-area="" asp-controller="Violation" asp-action="TreeFelling" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Деревьев</h4>
        <p>Незаконные рубка, выкапывание, уничтожение или повреждение до степени прекращения роста деревьев.</p>
    </a>
    <a asp-area="" asp-controller="Violation" asp-action="BushFelling" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Кустарников, лиан</h4>
        <p>Незаконные рубка, выкапывание, уничтожение или повреждение до степени прекращения роста кустарников и лиан.</p>
    </a>
    <a asp-area="" asp-controller="Violation" asp-action="DeadFelling" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Сухостойных деревьев</h4>
        <p>Присвоение (хищение) древесины буреломных, ветровальных деревьев.</p>
    </a>
</div>
<div class="list-group">
    <h4 class="text-uppercase">Повреждение</h4>
    <a asp-area="" asp-controller="Violation" asp-action="TreeFelling2" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Деревьев</h4>
        <p>Повреждение, не влекущее прекращения роста деревьев.</p>
    </a>
    <a asp-area="" asp-controller="Violation" asp-action="BushFelling2" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Кустарников, лиан</h4>
        <p>Повреждение, не влекущее прекращения роста кустарников и лиан.</p>
    </a>
    <a asp-area="" asp-controller="Violation" asp-action="BushFelling3" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Кустарничков</h4>
        <p>Уничтожение, выкапывание или повреждение кустарничков.</p>
    </a>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="RemovalOfAnthills" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Муравейников</h4>
        <p>Уничтожение или повреждение муравейников.</p>
    </a>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="RemovalOfSigns" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Знаков</h4>
        <p>Уничтожение или повреждение лесоустроительных или лесохозяйственных знаков.</p>
    </a>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="DamageToObjects" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Объектов</h4>
        <p>Повреждение объектов лесной инфраструктуры.</p>
    </a>
</div>
<div class="list-group">
    <h4 class="text-uppercase">Уничтожение или повреждение</h4>
    <a asp-area="" asp-controller="Violation" asp-action="SeedlingsFelling" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Сеянцев либо саженцев</h4>
        <p>Уничтожение или повреждение сеянцев либо саженцев в лесных питомниках.</p>
    </a>
    <a asp-area="" asp-controller="Violation" asp-action="PlantationFelling" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Лесных культур, плантаций, молодняка</h4>
        <p>Уничтожение или повреждение лесных культур, лесосеменных и маточных плантаций, молодняка естественного происхождения и подроста.</p>
    </a>
</div>
<div class="list-group">
    <h4 class="text-uppercase">Заготовка</h4>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="ResinFelling" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Живицы</h4>
        <p>Заготовка живицы, осуществляемая с нарушением установленных правил, а равно самовольно.</p>
    </a>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="ForestResourceFelling" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Недревесных лесных ресурсов</h4>
        <p>Заготовка и сбор недревесных лесных ресурсов.</p>
    </a>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="FoodResourceFelling" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Пищевых лесных ресурсов</h4>
        <p>Заготовка пищевых лесных ресурсов.</p>
    </a>
</div>
<div class="list-group">
    <h4 class="text-uppercase">Загрязнение</h4>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="ForestPollution" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Загрязнение лесов</h4>
        <p>Загрязнение лесов выбросами, радиоактивными и другими вредными веществами.</p>
    </a>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="ForestPollution2" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Размещение в лесах отходов</h4>
        <p>Размещение в лесах отходов производства и потребления.</p>
    </a>
</div>
<div class="list-group">
    <h4 class="text-uppercase">Другие нарушения</h4>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="ForestUse" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Самовольное использование лесов</h4>
        <p>Самовольное использование лесов для целей, предусмотренных Лесным кодексом Российской Федерации, с учетом назначения земель, на которых они располагаются.</p>
    </a>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="PlacementOfObjects" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Самовольное размещение объектов</h4>
        <p>Самовольное размещение объектов капитального строительства, объектов, не являющихся объектами капитального строительства.</p>
    </a>
    <a asp-area="" asp-controller="ViolationExtra" asp-action="RemovalOfSoils" class="list-group-item list-group-item-action list-group-item-success">
        <h4>Самовольное снятие, уничтожение или порча почв</h4>
        <p>Самовольное снятие, уничтожение или порча почв.</p>
    </a>
</div>